# docker-compose.yml

version: "3.9"
services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - postgresql:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d movies_database" ]
      interval: 10s
      timeout: 5s
      retries: 5
  django:
    build: movies_admin
    env_file:
      - .env
    volumes:
      - static:/opt/app/static
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: nginx:1.23.4
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static:/var/www/site/static
    depends_on:
      - django
    ports:
      - "80:80"
volumes:
  static:
  postgresql:
